name=ControlAnythingESP32
version=0.1.0
author=Brendan Mitchell <brendan.mitchell@sisu.us>
maintainer=Brendan Mitchell <brendan.mitchell@sisu.us>
sentence=TODO: one-line description of what this library controls
paragraph=
category=Uncategorized
url=https://github.com/BrendanJMitch/ControlAnythingESP32
architectures=esp32
